# SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - master

script:
  - go build ./...
  - go test -v -cover ./...

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
